name: Release Golang program

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
          architecture: amd64
      - name: Build Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o secret-santa
          tar -czvf secret-santa_windows_amd64.tar.gz secret-santa
          rm secret-santa
      - name: Build Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o secret-santa
          tar -czvf secret-santa_linux_amd64.tar.gz secret-santa
          rm secret-santa
      - name: Build MacOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o secret-santa
          tar -czvf secret-santa_macos_amd64.tar.gz secret-santa
          rm secret-santa
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: secret-santa_{{ linux, windows, macos }}_amd64.tar.gz
          asset_name: secret-santa_{{ linux, windows, macos }}_amd64.tar.gz
          asset_content_type: application/gzip
